### ISSUE TITLE
Unable to submit PR

### ISSUE THREAD

**Issue by ScottChesworth** [josephsl/addonUpdater#16]
Hi,

One of my Twitter followers noticed that A is currently used as the accelerator for the "check for add-on updates" option in the Tools menu. That conflicts with the "Manage add-ons" option. I've changed the accelerator to U locally, tried to submit a PR, but when I do git push origin localBranchName, I get this error:
fatal: unable to access 'https://github.com/josephsl/addonUpdater/': The requested URL returned error: 403

If anyone could nudge this newb toward what's causing that, it'd be much appreciated.

**Comment by josephsl** [comment]
Hi,

Pull requests: you may have cloned my repo which is set as origin in Git config. To send pull requests, you must first fork the repo, work on a branch other than "main", then send a pull request and tell GitHub to compare it against origin/main.

Check for add-on updates accelerator (letter A): this is intentional and I have no plans to change this at this time for a reason: Add-on Updater is a proof of concept, with the add-on scheduled to be discontinued once NVDA itself starts checking for add-on updates (this is actually being worked on by NV Access). Note that the letter U is taken by Unicode Braille Input, so that factored into this decision.

Thanks.

**Comment by josephsl** [comment]
Hi, at least thanks for bringing this up – this shows how popular Add-on Updater is and an additional data for NV Access to consider when designing their add-on store, which will replace Add-on Updater if the store does come to NVDA.
