### ISSUE TITLE
Wrong title of settings panel

### ISSUE THREAD

**Issue by CyrilleB79** [josephsl/addonUpdater#8]
Hi Joseph

Here is a minor issue found in add-on updater

 ### STR
1. Go to Notepad and create an application profile for Notepad
2. Open add-on updater settings panel in

### Actual result
The title of the panel indicates the Notepad profile

### Expected result
The panel's title should indicate "Normal configuration" as for the General settings panel.
At least it should not indicate the profile.

### Additional notes

Add-on updater should not be impacted by profiles:
1. If it is impacted by profiles, I think it is not desirable at all
2. If it is not impacted by pfofiles (and I think it is actually the case), the title of the panel is misleading.

For information, I think that "Update channel selector" add-on uses a setting panel not impacted by profiles.

**Comment by josephsl** [comment]
Hi, I’m thinking this is something beyond the add-on as it comes from NVDA Settings GUI. If it turns out the add-on is at fault, I’ll take a look at Update Channel Selector and resolve it in northern summer (June). Thanks.

**Comment by josephsl** [comment]
Hi,

Actually, Update Channel Selector panel title also reflects the profile in use at the moment, so it might be something to do with NVDA itself (beyond the scope of the add-on, sory).

Thanks.

**Comment by CyrilleB79** [comment]
> Actually, Update Channel Selector panel title also reflects the profile in use at the moment, so it might be something to do with NVDA itself (beyond the scope of the add-on, sory).

@josephsl, could you please double-check this?



Sorry to insist on this point. But I confirm on my side that the version of Update channel selector that I have (1.1) does not display the profile in the settings dialog title; it rather displays "NVDA Settings: Update channel (normal configuration)".

Moreover, when I select the category "Update channel" in the settings panel coming from another category (actually "Time Zoner"), I can hear:
"Editing profile normal configuration"

Just let me know. Thanks.

**Comment by josephsl** [comment]
Hi, I’ll take a look at some point in the future, but as far as actual configuration is concerned, Add-on Updater does not use confi.conf nor profiles at all – it has its own config map. Nevertheless I’ll look into it for summer. Thanks.

**Comment by CyrilleB79** [comment]
Thanks!

Could you then please reopen the issue?

**Comment by josephsl** [comment]
Hi, I see how Joe-Manuel did it – panel activation/deactivation methods are used. As I mentioned earlier Add-on Updater does not use config.conf facility, but knowing that folks can navigate through settings categories, I’ll do something about profile announcements (unless you would like to write a pull request). Thanks.

**Comment by CyrilleB79** [comment]
If you can fix it on your side, I'd be grateful. But I know that you have a lot of work these times.

  If you cannot, I keep this issue apart and will make a PR when I have time. But it may be not so soon.

**Comment by josephsl** [comment]
Hi, I’ll take care of it in May at the earliest. Thanks.

**Comment by XLTechie** [comment]
@CyrilleB79 On the add-ons list, I reported back in maybe April or May, looking into this.
The problem comes from NVDA's side: there is no provision for add-ons to specify that their config panels are profile-agnostic.

The way Update Channel Selector does it, is to remove the name of the active profile. That causes the config panels to "lie" about what the profile name is. They are still operating with the active profile, but its name has been removed so they don't think there is one.
That add-on then uses direct writes into the profile 0 dictionary to save its settings.

Unfortunately, I found all kinds of corner cases with this approach, that make it undesirable and tricky. There are situations where the profile name is never re-established, for example, resulting in the system profile **and** one of the other profiles, being left with no name as far as part of NVDA is concerned, but still having a name as far as other parts are concerned.

I abandoned this approach for use in Speech Logger, and went with another one that just shows a "please configure using the normal profile" type message in the config panel, for all profiles that aren't the normal one.

This really needs to be fixed at the NVDA level.

**Comment by CyrilleB79** [comment]
If there is not already an issue in NVDA bug tracker for tis, would you mind creating one? With the description of the wanted behaviour, but also with the analysis you have already done on the situations of the existing add-ons and the imperfect workaround they use.

If there is such an issue or if you create a new one, could you add here the reference?
Thanks.

**Comment by XLTechie** [comment]
I haven't yet gotten around to creating an issue for this that I can remember. 
If I do, I'll reference it here.

**Comment by josephsl** [comment]
Hi,

 2023 update: unless this issue is revisited by someone before NVDA 2023.3 is released, I will close it when Add-on Updater is discontinued.

Thanks.

**Comment by josephsl** [comment]
Hi all,

2024 update: I'm in favor of closing this now that NVDA Core gains abiilty to notify users of add-on updates (the original goal of the add-on).
Thanks.

**Comment by josephsl** [comment]
Hi,

I understand that keeping the issue open may offer opportunities for someone to take care of it or perhaps resolve it when working on something based on this code base. However, as I said a while ago, the code for this add-on will become read-only, and as noted by Luke, this is beyond the scope of the add-on at this point (yes, the add-on is being officially discontinued).

Thanks (closing).

**Comment by XLTechie** [comment]
@CyrilleB79 I'll put a "known-issues" comment in the readme or some such.

But there is no real point to keeping this open since we're not going to fix it, and any true fix has to come from the NVDA side per my comment above.

I still do need to create an NVDA issue about this, however, and link to it here, which I will.

**Comment by XLTechie** [comment]
This is now mentioned in the Add-on Updater readme, as one of the items in the "IMPORTANT NOTES" section.
